version: '3.8'

services:
  app:
    build: .
    container_name: mrp_pcp
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    networks:
      - giv_network

networks:
  giv_network:
    external: true
